name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.7.app

    - name: Build and test
      run: xcodebuild clean build test -workspace CakeClub.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.7,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
